# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7da8886780f0631df49644adc09b82577f1ab3325f101b5277e94c4d309e0eb80d81ff177020e4de8699c4f1b4d808ba146ae8729bb31ba3441773776031c8

test:
  secret_key_base: f453bba96497f88d99b5d875f4fc8df0768973a131441c17a211472566b12fae6c2bbf2129418e3b5853c6cb366f6a28626abe4ee466e31ae5bb66cc947d9657

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
